# Generated by Django 4.0.4 on 2022-04-23 04:04

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='DNI',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='Direccion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='Entidad',
            field=models.CharField(choices=[('Persona', 'Persona'), ('Empresa', 'Empresa')], default='Persona', max_length=7),
        ),
        migrations.AlterField(
            model_name='user',
            name='Telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
